[theme]
primaryColor = "#19C37D"
backgroundColor = "#343541"
secondaryBackgroundColor = "#444654"
textColor = "#ECECF1"
font = "sans serif"

[server]
enableCORS = true
enableXsrfProtection = true
maxUploadSize = 5

[browser]
gatherUsageStats = false

[runner]
magicEnabled = true
installTracer = false
fixMatplotlib = true

[client]
toolbarMode = "minimal"
showErrorDetails = false

